fix(meta): Fix the regression in the Nix setup workflow
Fix the error like this:

 error: creating directory "/home/runner/.cache/nix": Permission denied